apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: trento-runner
  annotations:
    github.com/project-slug: nelsonkopliku/runner
  tags:
      - sap
      - pacemaker-cluster
      - ha-config-checks
spec:
  type: service
  lifecycle: production
  owner: trento-team
